name: Bug Report
description: Report a problem with Worn Path
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: e.g. 1.21.11
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Worn Path Version
      placeholder: e.g. 1.3.0
    validations:
      required: true

  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      options:
        - Fabric
        - NeoForge
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
