modLoader = "javafml"
loaderVersion = "[11,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "worn_path"
version = "${version}"
displayName = "Worn Path"
authors = "edward3h"
description = '''
Where players walk, paths may appear.
'''
#logoFile = ""

[[dependencies.worn_path]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worn_path]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worn_path]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "worn_path.mixins.json"
